version: '2'
services:
  jeopardy-www:
    build: .
    hostname: jeopardy
    environment:
      - DBNAME=jeopardy
      - DBUSER=jeopardy
      - DBPASS=password
      - DBHOST=jeopardy-mongodb
      - DBPORT=27017
    container_name: 'jeopardy-www'
    ports:
      - '5000:5000'
    volumes:
      - '.:/opt/src'
    networks:
      - app
    links:
      - 'jeopardy-mongodb:jeopardy-mongodb'
    entrypoint: /opt/src/build/run
    depends_on:
      - jeopardy-mongodb

  jeopardy-mongodb:
    hostname: jeopardy-monogodb
    container_name: jeopardy-mongodb
    image: mongo:latest
    networks:
      - app
    ports:
      - '27017:27017'
    volumes:
      - jeopardy-mongodb-storage:/data/mongo

volumes:
  jeopardy-mongodb-storage: 

networks:
  default:
    driver: bridge
  app:
    driver: bridge
