version: '2'
services:
  jeopardy-www:
    build: .
    hostname: jeopardy
    environment:
      - DBNAME=jeopardy
      - DBUSER=jeopardy
      - DBPASS=password
      - DBHOST=jeopardy-mongodb
      - DBPORT=27017
    container_name: 'jeopardy-www'
    ports:
      - '5000:5000'
    volumes:
      - '.:/opt/src'
    networks:
      - app
    links:
      - 'jeopardy-mongodb:jeopardy-mongodb'
      #- 'sabnzbd:sabnzbd'
    entrypoint: /opt/src/util/run
    depends_on:
      - jeopardy-mongodb

  jeopardy-mongodb:
    hostname: jeopardy-monogodb
    container_name: jeopardy-mongodb
    image: mongo:latest
    networks:
      - app
    ports:
      - '27017:27017'
    volumes:
      - jeopardy-mongodb-storage:/data/mongo
  
  #sabnzbd:
  #  image: theraccoonbear/sabnzbd:latest
  #  container_name: sabnzbd
  #  ports:
  #    - '9090:9090'
  #    #- '8080:8080'
  #  volumes:
  #    - './src:/opt/src'
  #    #- '.:/opt/src'
  #   
  #  networks:
  #    - app

volumes:
  jeopardy-mongodb-storage: 

networks:
  default:
    driver: bridge
  app:
    driver: bridge
