#!/bin/bash

REPO_DIR=/opt/src/special/text-handlebars
REPO_LIB_DIR=$REPO_DIR/lib/Text
LIB_DIR=/opt/src/lib/Text

if [ -d "$REPO_DIR" ]; then
  echo "Custom Text::Handlebars found already downloadedd"
	cd $REPO_DIR
	echo "Getting current..."
	git stash
	git checkout issue-9
	git pull
else
	echo "Did not find Text::Handlebars, installing custom..."

	git clone https://github.com/theraccoonbear/text-handlebars.git $REPO_DIR
	
	cd $REPO_DIR
	git fetch
	git checkout issue-9
	git pull
fi


if [ -h "$LIB_DIR" ]; then
	echo "Text::Handlebars library already linked."
else
	echo "Linking Text::Handlebars library..."
	ln -s $REPO_LIB_DIR $LIB_DIR
fi

echo "Done."