#!/usr/bin/env bash

cd /opt/src
./util/git-setup
./util/install-modules
./util/handle-special

#perl -I /opt/src/modules/lib/perl5 /opt/src/modules/bin/plackup -R /opt/src/app/bin,/opt/src/app/lib -r /opt/src/app/bin/app.psgi
#/opt/src/modules/bin/plackup -R /opt/src/app/bin,/opt/src/app/lib -r /opt/src/app/bin/app.psgi
perl -I /opt/src/modules/lib/perl5 `which plackup`  --server Twiggy -R /opt/src/app/bin,/opt/src/app/lib -r /opt/src/app/bin/app.psgi
